'use client'

import { Canvas, useFrame } from '@react-three/fiber'
import { OrbitControls, PerspectiveCamera } from '@react-three/drei'
import { useRef, useState } from 'react'
import type { Mesh } from 'three'
import { Activity, Box, Check, ChevronRight, CircleDot, FileUp, Gauge, Layers3, Play, RotateCcw, ScanLine, ShieldCheck, SlidersHorizontal, Sparkles, Upload, Workflow } from 'lucide-react'

function AnatomyScene({ opacity, isolate }: { opacity: number; isolate: boolean }) {
  const organ = useRef<Mesh>(null)
  useFrame((_, delta) => { if (organ.current) organ.current.rotation.y += delta * 0.22 })
  return <>
    <ambientLight intensity={1.5} /><directionalLight position={[4, 5, 4]} intensity={3} color="#d9fbff" /><pointLight position={[-3, 1, 2]} intensity={2} color="#55d9eb" />
    <group rotation={[0.1, -0.2, 0]}>
      <mesh scale={[0.85, 1.45, 0.5]} position={[0, 0, 0]}><capsuleGeometry args={[0.7, 1.25, 12, 24]} /><meshPhysicalMaterial color="#4db9c9" transparent opacity={opacity} roughness={0.36} transmission={0.12} /></mesh>
      {!isolate && <mesh position={[-0.18, 0.05, -0.25]}><cylinderGeometry args={[0.11, 0.15, 2.8, 20]} /><meshPhysicalMaterial color="#d4f8fa" transparent opacity={0.76} /></mesh>}
      <mesh ref={organ} visible={!isolate || isolate} position={[0.25, 0.35, 0.42]} scale={[1.28, 0.82, 0.8]}><sphereGeometry args={[0.42, 32, 22]} /><meshPhysicalMaterial color="#f39caf" emissive="#3d1723" emissiveIntensity={0.3} roughness={0.3} /></mesh>
      {[-0.7, -0.38, -0.06, 0.26, 0.58, 0.9].map((y) => <mesh key={y} position={[0, y, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.58, 1]}><torusGeometry args={[0.5, 0.025, 8, 32, Math.PI]} /><meshBasicMaterial color="#8de1ea" transparent opacity={0.48} /></mesh>)}
    </group>
  </>
}

const navItems = [{ label: 'Case overview', icon: CircleDot }, { label: 'Imaging pipeline', icon: ScanLine }, { label: 'Anatomy models', icon: Box }, { label: 'Surgical simulation', icon: Workflow }]

export default function Page() {
  const [depth, setDepth] = useState(42), [opacity, setOpacity] = useState(78), [rotating, setRotating] = useState(true), [isolated, setIsolated] = useState(false), [simulated, setSimulated] = useState(false), [processing, setProcessing] = useState(false)
  return <div className="grid-bg min-h-screen">
    <header className="glass flex h-16 items-center justify-between border-b border-[#20384e] px-5 md:px-7"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-lg border border-[#5dd8e7]/50 bg-[#5dd8e7]/15 font-bold text-[#5dd8e7]">S</div><div><div className="text-sm font-semibold tracking-wide text-white">SDAPM</div><div className="mono text-[9px] uppercase tracking-[.22em] text-slate-500">Precision medicine OS</div></div></div><div className="hidden items-center gap-7 text-[11px] text-slate-400 md:flex"><span>CASE <b className="text-slate-200">ONC-24018</b></span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#83e4c0] shadow-[0_0_10px_#83e4c0]" />Systems nominal</span><span className="flex size-8 items-center justify-center rounded-full bg-slate-700 text-slate-200">DR</span></div></header>
    <div className="flex min-h-[calc(100vh-4rem)]"><aside className="glass hidden w-60 shrink-0 flex-col border-r border-[#20384e] p-4 lg:flex"><div className="px-3 pb-4 pt-2 text-[10px] uppercase tracking-[.2em] text-slate-500">Workspace</div><nav className="flex flex-col gap-1">{navItems.map(({ label, icon: Icon }, i) => <button key={label} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${i === 0 ? 'border-r-2 border-[#5dd8e7] bg-[#5dd8e7]/10 text-[#b9f4f7]' : 'text-slate-400 hover:text-white'}`}><Icon className={i === 0 ? 'text-[#5dd8e7]' : ''} />{label}</button>)}</nav><div className="mt-auto rounded-xl border border-[#20384e] bg-[#07111d]/70 p-3"><div className="flex justify-between text-xs"><span className="text-slate-400">Compute pool</span><span className="text-[#83e4c0]">82%</span></div><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-full w-[82%] rounded-full bg-gradient-to-r from-[#5dd8e7] to-[#83e4c0]" /></div><div className="mono mt-2 text-[10px] text-slate-500">GPU-A100 / 04 online</div></div></aside>
      <main className="min-w-0 flex-1 overflow-hidden p-5 lg:p-7"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="mono mb-2 text-xs text-[#5dd8e7]">CASE / ONC-24018 / ACTIVE REVIEW</div><h1 className="text-2xl font-semibold tracking-tight text-white md:text-3xl">Patient-specific anatomy workspace</h1><p className="mt-2 text-sm text-slate-400">Review reconstructed structures and test surgical approach hypotheses.</p></div><button className="rounded-lg border border-[#5dd8e7]/40 bg-[#5dd8e7]/10 px-4 py-2.5 text-sm font-medium text-[#5dd8e7] hover:bg-[#5dd8e7]/20"><Sparkles className="mr-2 inline-block" />New case</button></div>
        <section className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{[['Processing status', processing ? 'Processing' : 'Completed', processing ? 'text-amber-300' : 'text-[#83e4c0]'], ['Structures reconstructed', '12', 'text-white'], ['Model confidence', '96.8%', 'text-white'], ['Simulation margin', '4.2 mm', 'text-white']].map(([label, value, color]) => <div key={label} className="rounded-xl border border-[#20384e] bg-[#0d1c2d]/80 p-4"><div className="text-xs text-slate-500">{label}</div><strong className={`mt-2 block text-xl ${color}`}>{value}</strong></div>)}</section>
        <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-hidden rounded-2xl border border-[#20384e] bg-[#0d1c2d]/75"><div className="flex items-center justify-between border-b border-[#20384e] px-5 py-4"><div><div className="text-sm font-semibold text-white">3D anatomy model</div><div className="mt-1 text-xs text-slate-500">Reconstruction / organ segmentation / v2.4</div></div><div className="flex gap-2"><button onClick={() => setRotating(!rotating)} className="rounded-md border border-[#20384e] px-3 py-1.5 text-xs text-slate-300 hover:border-[#5dd8e7]/50">{rotating ? 'Pause' : 'Rotate'}</button><button onClick={() => { setRotating(true); setIsolated(false) }} className="rounded-md border border-[#20384e] p-2 text-slate-300 hover:border-[#5dd8e7]/50" aria-label="Reset view"><RotateCcw /></button></div></div><div className="relative h-[360px] bg-[#091522] md:h-[420px]"><Canvas dpr={[1, 2]} camera={{ position: [2.9, 1.5, 4.4], fov: 32 }}><PerspectiveCamera makeDefault position={[2.9, 1.5, 4.4]} /><AnatomyScene opacity={opacity / 100} isolate={isolated} /><OrbitControls autoRotate={rotating} autoRotateSpeed={0.65} enableDamping /></Canvas><div className="pointer-events-none absolute left-5 top-5 text-[10px] uppercase tracking-widest text-slate-500">Anterior / axial reference</div><div className="pointer-events-none absolute bottom-4 left-5 flex items-center gap-2 text-[10px] text-slate-500"><i className="size-2 rounded-full bg-[#5dd8e7]" />Segmented anatomy <i className="ml-3 size-2 rounded-full bg-rose-300" />Lesion region</div></div><div className="scanline" /><div className="flex items-center justify-between border-t border-[#20384e] px-5 py-3 text-xs"><span className="mono text-slate-500">MESH · 842K FACES · 0.42MM VOXEL</span><button onClick={() => setIsolated(!isolated)} className="text-[#5dd8e7] hover:text-white">{isolated ? 'Show target' : 'Isolate target'} <ChevronRight className="inline-block" /></button></div></div>
          <div className="flex flex-col gap-5"><Panel title="Processing pipeline" subtitle="CT_Abdomen_01.nii.gz" badge="READY"><div className="flex flex-col gap-4 text-xs">{['DICOM normalization', 'TotalSegmentator', 'Mesh optimization'].map((item, i) => <div className="flex gap-3" key={item}><span className="flex size-5 items-center justify-center rounded-full bg-[#83e4c0]/15 text-[#83e4c0]"><Check /></span><div><div className="text-slate-200">{item}</div><div className="mono mt-1 text-slate-500">Completed · {['00:42', '02:51', '00:45'][i]}</div></div></div>)}</div><button onClick={() => { setProcessing(true); setTimeout(() => setProcessing(false), 1800) }} className="mt-5 w-full rounded-lg border border-[#20384e] py-2.5 text-xs text-slate-300 hover:border-[#5dd8e7]/50">Reprocess scan</button></Panel><Panel title="Surgical simulation" subtitle="Live"><div className="flex flex-col gap-5"><label className="text-xs text-slate-400">Cutting plane depth <span className="mono float-right text-[#5dd8e7]">{depth} mm</span><input value={depth} onChange={(e) => setDepth(+e.target.value)} type="range" min="10" max="80" className="range mt-3 w-full" /></label><label className="text-xs text-slate-400">Tissue opacity <span className="mono float-right text-[#5dd8e7]">{opacity}%</span><input value={opacity} onChange={(e) => setOpacity(+e.target.value)} type="range" min="20" max="100" className="range mt-3 w-full" /></label><button onClick={() => setSimulated(true)} className="rounded-lg bg-[#5dd8e7] px-4 py-2.5 text-sm font-semibold text-[#07111d] hover:bg-white"><Play className="mr-2 inline-block" />Run cut simulation</button>{simulated && <div className="rounded-lg border border-[#83e4c0]/30 bg-[#83e4c0]/5 p-3 text-xs text-[#83e4c0]">Plane intersects target volume · estimated resection: 12.4 cm³</div>}</div></Panel></div></section>
      </main></div></div>
}

function Panel({ title, subtitle, badge, children }: { title: string; subtitle: string; badge?: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-[#20384e] bg-[#0d1c2d]/75 p-5"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-semibold text-white">{title}</div><div className="mt-1 text-xs text-slate-500">{subtitle}</div></div>{badge && <span className="rounded-full bg-[#83e4c0]/10 px-2 py-1 text-[10px] text-[#83e4c0]">{badge}</span>}</div>{children}</div> }
